site_name: Linguagem de Programação I
site_description: Lista de exercícios da disciplina de Linguagem de Programação I do curso de Analise e Desenvolvimento de Sistemas da FATEC de Franca.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
google_analytics: ['UA-70830801-6', 'getuliovinicius.github.io/linguagem.programacao-I/']
repo_url: https://github.com/getuliovinicius/linguagem.programacao-I
repo_name: GitHub
edit_uri: blob/master/docs/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
  - Inicio: index.md
theme: readthedocs

